# Generated by Django 4.2.30 on 2026-08-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.TextField(help_text='Escribe aquí la historia de la asociación.', verbose_name='Historia de AMVI')),
                ('mision', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('quienes_somos', models.TextField(verbose_name='Quiénes somos')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de Nosotros',
                'verbose_name_plural': 'Información de Nosotros',
            },
        ),
    ]
