# Generated by Django 6.1 on 2026-08-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_informacionnosotros'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionnosotros',
            name='valores',
            field=models.TextField(default='Valores de la Asociación AMVI', verbose_name='Valores'),
            preserve_default=False,
        ),
    ]
